# Generated by Django 5.1.7 on 2025-11-04 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_object_id', models.UUIDField(help_text='ID du document signé')),
                ('signature_request_object_id', models.UUIDField(help_text='ID du SignatureRequest')),
                ('signature_field_name', models.CharField(help_text='Nom du champ PDF (format: {signer_uuid}-{name} slugifié)', max_length=255)),
                ('otp_code', models.CharField(help_text='Code OTP validé (copie immuable depuis SignatureRequest)', max_length=6)),
                ('otp_generated_at', models.DateTimeField(help_text='Date/heure génération OTP (copie immuable)')),
                ('otp_validated_at', models.DateTimeField(help_text='Date/heure validation OTP (copie immuable)')),
                ('otp_validated', models.BooleanField(help_text='OTP validé avec succès')),
                ('ip_address', models.GenericIPAddressField(help_text='Adresse IP du signataire')),
                ('user_agent', models.TextField(help_text='User-Agent navigateur')),
                ('referer', models.URLField(blank=True, help_text='Referer HTTP')),
                ('signature_timestamp', models.DateTimeField(help_text='Date/heure signature (serveur NTP-sync)')),
                ('pdf_hash_before', models.CharField(help_text='Hash SHA-256 du PDF AVANT signature', max_length=64)),
                ('pdf_hash_after', models.CharField(help_text='Hash SHA-256 du PDF APRÈS signature', max_length=64)),
                ('certificate_pem', models.TextField(help_text='Certificat X.509 complet (format PEM)')),
                ('certificate_fingerprint', models.CharField(help_text='Empreinte SHA-256 du certificat', max_length=64)),
                ('certificate_subject_dn', models.CharField(help_text='Subject DN (CN, O, Email)', max_length=255)),
                ('certificate_issuer_dn', models.CharField(help_text='Issuer DN (CA Hestia)', max_length=255)),
                ('certificate_valid_from', models.DateTimeField(help_text='Début validité certificat')),
                ('certificate_valid_until', models.DateTimeField(help_text='Fin validité certificat')),
                ('tsa_timestamp', models.CharField(blank=True, help_text='Token TSA (si utilisé)', max_length=128)),
                ('tsa_response', models.BinaryField(blank=True, help_text='Réponse complète TSA RFC 3161', null=True)),
                ('document_content_type', models.ForeignKey(help_text='Type de document signé', on_delete=django.db.models.deletion.CASCADE, related_name='signature_metadata_documents', to='contenttypes.contenttype')),
                ('signature_request_content_type', models.ForeignKey(help_text='Type de SignatureRequest (Bail, EtatLieux, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='signature_metadata_requests', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Métadonnées de signature',
                'verbose_name_plural': 'Métadonnées de signatures',
                'ordering': ['signature_timestamp'],
                'indexes': [models.Index(fields=['document_content_type', 'document_object_id'], name='signature_s_documen_73a9de_idx'), models.Index(fields=['signature_request_content_type', 'signature_request_object_id'], name='signature_s_signatu_f708bc_idx'), models.Index(fields=['signature_timestamp'], name='signature_s_signatu_14e3ba_idx')],
            },
        ),
    ]
