# Generated by Django 5.1.7 on 2025-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='additionnal_description',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='annexes',
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='type_charges',
            field=models.CharField(blank=True, choices=[('forfaitaires', 'Forfaitaires'), ('provisionnelles', 'Provisionnelles')], max_length=20, null=True, verbose_name='Type de charges'),
        ),
    ]
