# Generated by Django 5.1.7 on 2025-10-03 21:53

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBien',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('identifiant_fiscal', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Identifiant fiscal')),
                ('regime_juridique', models.CharField(blank=True, choices=[('monopropriete', 'Monopropriété'), ('copropriete', 'Copropriété')], default=None, max_length=20, null=True, verbose_name='Régime juridique')),
                ('type_bien', models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('maison', 'Maison')], default=None, max_length=20, null=True, verbose_name='Type de bien')),
                ('etage', models.CharField(blank=True, max_length=10)),
                ('porte', models.CharField(blank=True, max_length=10)),
                ('dernier_etage', models.BooleanField(blank=True, default=None, null=True)),
                ('periode_construction', models.CharField(blank=True, choices=[('avant 1946', 'Avant 1946'), ('1946-1970', '1946-1970'), ('1971-1990', '1971-1990'), ('1990-2005', '1990-2005'), ('apres 1990', 'Après 1990'), ('apres 2005', 'Après 2005')], default=None, max_length=20, null=True, verbose_name='Période de construction')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='En m²', max_digits=8, null=True)),
                ('meuble', models.BooleanField(blank=True, default=None, null=True, verbose_name='Meublé')),
                ('classe_dpe', models.CharField(blank=True, choices=[('A', 'A (≤ 70 kWh/m²/an)'), ('B', 'B (71 à 110 kWh/m²/an)'), ('C', 'C (111 à 180 kWh/m²/an)'), ('D', 'D (181 à 250 kWh/m²/an)'), ('E', 'E (251 à 330 kWh/m²/an)'), ('F', 'F (331 à 420 kWh/m²/an)'), ('G', 'G (> 420 kWh/m²/an)'), ('NA', 'Non soumis à DPE')], default=None, max_length=2, null=True, verbose_name='Classe énergétique DPE')),
                ('depenses_energetiques', models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='Dépenses énergétiques théoriques (€/an)')),
                ('annexes_privatives', models.JSONField(blank=True, default=None, null=True)),
                ('annexes_collectives', models.JSONField(blank=True, default=None, null=True)),
                ('information', models.JSONField(blank=True, default=None, null=True)),
                ('pieces_info', models.JSONField(blank=True, default=None, help_text='Détail des pièces: chambres, sallesDeBain, cuisines, etc.', null=True)),
                ('chauffage_type', models.CharField(blank=True, choices=[('collectif', 'Collectif'), ('individuel', 'Individuel')], default=None, max_length=20, null=True)),
                ('chauffage_energie', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('eau_chaude_type', models.CharField(blank=True, choices=[('collectif', 'Collectif'), ('individuel', 'Individuel')], default=None, max_length=20, null=True)),
                ('eau_chaude_energie', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bien',
                'verbose_name_plural': 'historical biens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('solidaires', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, default=None, null=True)),
                ('date_fin', models.DateField(blank=True, default=None, null=True)),
                ('created_from', models.CharField(choices=[('bail', 'Bail'), ('quittance', 'Quittance'), ('etat_lieux', 'État des lieux'), ('manual', 'Manuel')], default='manual', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bien', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.bien')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mandataire', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.mandataire')),
            ],
            options={
                'verbose_name': 'historical Location',
                'verbose_name_plural': 'historical Locations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
