# Generated by Django 5.1.7 on 2025-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_historicalbien_historicallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='attestation_mrh',
            field=models.FileField(blank=True, default=None, help_text="Attestation d'assurance Multirisques Habitation", null=True, upload_to='locataire_documents/mrh/'),
        ),
        migrations.AddField(
            model_name='locataire',
            name='caution_solidaire_document',
            field=models.FileField(blank=True, default=None, help_text='Document de caution solidaire (si caution_requise=True)', null=True, upload_to='locataire_documents/caution/'),
        ),
    ]
