# Generated by Django 5.1.7 on 2025-08-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_remove_bien_additionnal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='prenom',
            field=models.CharField(db_column='prenom', max_length=100),
        ),
        migrations.RenameField(
            model_name='personne',
            old_name='prenom',
            new_name='firstName',
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(db_column='nom', max_length=100),
        ),
        migrations.RenameField(
            model_name='personne',
            old_name='nom',
            new_name='lastName',
        ),
    ]
