# Generated by Django 5.1.7 on 2025-10-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_locataire_attestation_mrh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locataire',
            name='attestation_mrh',
        ),
        migrations.RemoveField(
            model_name='locataire',
            name='caution_solidaire_document',
        ),
    ]
