# Generated by Django 5.1.7 on 2025-08-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_personne_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentterms',
            name='dernier_montant_loyer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant du dernier loyer si locataire dans les 18 derniers mois', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentterms',
            name='locataire_derniers_18_mois',
            field=models.BooleanField(blank=True, help_text='Le bien a-t-il eu un locataire dans les 18 derniers mois', null=True),
        ),
        migrations.AddField(
            model_name='rentterms',
            name='premiere_mise_en_location',
            field=models.BooleanField(blank=True, help_text='Première mise en location du bien', null=True),
        ),
    ]
