# Generated by Django 5.1.7 on 2025-08-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_rentterms_dernier_montant_loyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='annexes_collectives',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='annexes_privatives',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='classe_dpe',
            field=models.CharField(blank=True, choices=[('A', 'A (≤ 70 kWh/m²/an)'), ('B', 'B (71 à 110 kWh/m²/an)'), ('C', 'C (111 à 180 kWh/m²/an)'), ('D', 'D (181 à 250 kWh/m²/an)'), ('E', 'E (251 à 330 kWh/m²/an)'), ('F', 'F (331 à 420 kWh/m²/an)'), ('G', 'G (> 420 kWh/m²/an)'), ('NA', 'Non soumis à DPE')], max_length=2, null=True, verbose_name='Classe énergétique DPE'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='depenses_energetiques',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Dépenses énergétiques théoriques (€/an)'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='dernier_etage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='information',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='meuble',
            field=models.BooleanField(blank=True, null=True, verbose_name='Meublé'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='pieces_info',
            field=models.JSONField(blank=True, help_text='Détail des pièces: chambres, sallesDeBain, cuisines, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='regime_juridique',
            field=models.CharField(blank=True, choices=[('monopropriete', 'Monopropriété'), ('copropriete', 'Copropriété')], max_length=20, null=True, verbose_name='Régime juridique'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En m²', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type_bien',
            field=models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('maison', 'Maison')], max_length=20, null=True, verbose_name='Type de bien'),
        ),
    ]
