# Generated by Django 5.1.7 on 2025-10-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_file_fields_from_locataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentterms',
            name='dernier_mois_loye',
            field=models.DateField(blank=True, default=None, help_text='Mois de fin du dernier loyer perçu (dernier mois où le bien était loué)', null=True),
        ),
    ]
