# Generated by Django 5.1.7 on 2025-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_rentterms_dernier_mois_loye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentterms',
            name='dernier_mois_loye',
        ),
        migrations.AddField(
            model_name='rentterms',
            name='dernier_loyer_annee',
            field=models.CharField(blank=True, default=None, help_text='Année du dernier loyer perçu (ex: 2024)', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='rentterms',
            name='dernier_loyer_mois',
            field=models.CharField(blank=True, default=None, help_text='Mois du dernier loyer perçu (ex: janvier, février...)', max_length=20, null=True),
        ),
    ]
