# Generated by Django 5.1.7 on 2025-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_make_bien_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentterms',
            name='zone_tendue',
            field=models.BooleanField(blank=True, help_text="Situé en zone d'encadrement des loyers", null=True),
        ),
    ]
