# Generated by Django 5.1.7 on 2025-10-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_remove_rentterms_dernier_mois_loye_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentterms',
            name='dernier_loyer_annee',
        ),
        migrations.RemoveField(
            model_name='rentterms',
            name='dernier_loyer_mois',
        ),
        migrations.AddField(
            model_name='rentterms',
            name='dernier_loyer_periode',
            field=models.CharField(blank=True, default=None, help_text='Mois et année du dernier loyer perçu (format YYYY-MM, ex: 2024-03)', max_length=7, null=True),
        ),
    ]
