# Generated by Django 5.1.7 on 2025-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_make_zone_tendue_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentterms',
            name='permis_de_louer',
            field=models.BooleanField(blank=True, help_text='Indique si un permis de louer est requis pour ce bien', null=True, verbose_name='Permis de louer'),
        ),
    ]
