# Generated by Django 5.1.7 on 2025-10-10 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_remove_rentterms_dernier_loyer_annee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Compte utilisateur associé (créé automatiquement via email)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes', to=settings.AUTH_USER_MODEL),
        ),
    ]
