# Generated by Django 5.1.7 on 2025-09-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_make_permis_de_louer_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentterms',
            name='justificatif_complement_loyer',
            field=models.TextField(blank=True, default=None, help_text="Justification du complément de loyer en cas de dépassement du plafond d'encadrement", null=True, verbose_name='Justification du complément de loyer'),
        ),
    ]
