# Generated by Django 5.1.7 on 2025-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_personne_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentterms',
            name='honoraires_bail_par_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Tarif des honoraires de bail au m² (€/m²). Plafonds légaux : 12€/m² (zone très tendue), 10€/m² (zone tendue), 8€/m² (zone normale).', max_digits=6, null=True, verbose_name='Honoraires de bail par m²'),
        ),
        migrations.AddField(
            model_name='rentterms',
            name='honoraires_bail_part_bailleur_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Pourcentage des honoraires de bail à la charge du bailleur (0-100%). La part locataire ne peut excéder 50%.', max_digits=5, null=True, verbose_name='Part bailleur (%)'),
        ),
        migrations.AddField(
            model_name='rentterms',
            name='honoraires_edl_par_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text="Tarif des honoraires d'état des lieux au m² (€/m²). Maximum 3€/m².", max_digits=5, null=True, verbose_name='Honoraires EDL par m²'),
        ),
        migrations.AddField(
            model_name='rentterms',
            name='honoraires_edl_part_bailleur_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Pourcentage des honoraires EDL à la charge du bailleur (0-100%). Répartition libre entre bailleur et locataire.', max_digits=5, null=True, verbose_name='Part bailleur EDL (%)'),
        ),
        migrations.AddField(
            model_name='rentterms',
            name='mandataire_fait_edl',
            field=models.BooleanField(default=False, help_text="Indique si le mandataire est en charge de la réalisation de l'EDL", verbose_name="Le mandataire réalise l'état des lieux"),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='zone_tendue',
            field=models.BooleanField(blank=True, default=None, help_text='Situé en zone tendue (déséquilibre offre/demande de logements)', null=True),
        ),
    ]
