# Generated by Django 5.1.7 on 2025-09-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_make_justificatif_complement_loyer_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailleur',
            name='personne',
            field=models.ForeignKey(blank=True, default=None, help_text='Personne physique bailleur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bailleurs', to='location.personne'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='signataire',
            field=models.ForeignKey(blank=True, default=None, help_text='Personne physique qui signe pour le bailleur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bailleurs_signes', to='location.personne'),
        ),
        migrations.AlterField(
            model_name='bailleur',
            name='societe',
            field=models.ForeignKey(blank=True, default=None, help_text='Société bailleur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bailleurs', to='location.societe'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='annexes_collectives',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='annexes_privatives',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='chauffage_type',
            field=models.CharField(blank=True, choices=[('collectif', 'Collectif'), ('individuel', 'Individuel')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='classe_dpe',
            field=models.CharField(blank=True, choices=[('A', 'A (≤ 70 kWh/m²/an)'), ('B', 'B (71 à 110 kWh/m²/an)'), ('C', 'C (111 à 180 kWh/m²/an)'), ('D', 'D (181 à 250 kWh/m²/an)'), ('E', 'E (251 à 330 kWh/m²/an)'), ('F', 'F (331 à 420 kWh/m²/an)'), ('G', 'G (> 420 kWh/m²/an)'), ('NA', 'Non soumis à DPE')], default=None, max_length=2, null=True, verbose_name='Classe énergétique DPE'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='depenses_energetiques',
            field=models.CharField(blank=True, default=None, max_length=400, null=True, verbose_name='Dépenses énergétiques théoriques (€/an)'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='dernier_etage',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='eau_chaude_type',
            field=models.CharField(blank=True, choices=[('collectif', 'Collectif'), ('individuel', 'Individuel')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='information',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='meuble',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Meublé'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='periode_construction',
            field=models.CharField(blank=True, choices=[('avant 1946', 'Avant 1946'), ('1946-1970', '1946-1970'), ('1971-1990', '1971-1990'), ('1990-2005', '1990-2005'), ('apres 1990', 'Après 1990'), ('apres 2005', 'Après 2005')], default=None, max_length=20, null=True, verbose_name='Période de construction'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='pieces_info',
            field=models.JSONField(blank=True, default=None, help_text='Détail des pièces: chambres, sallesDeBain, cuisines, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='regime_juridique',
            field=models.CharField(blank=True, choices=[('monopropriete', 'Monopropriété'), ('copropriete', 'Copropriété')], default=None, max_length=20, null=True, verbose_name='Régime juridique'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='superficie',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='En m²', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type_bien',
            field=models.CharField(blank=True, choices=[('appartement', 'Appartement'), ('maison', 'Maison')], default=None, max_length=20, null=True, verbose_name='Type de bien'),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='date_emission_ci',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='revenu_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_debut',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='date_fin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='mandataire',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.mandataire'),
        ),
        migrations.AlterField(
            model_name='mandataire',
            name='date_fin_mandat',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='iban',
            field=models.CharField(blank=True, default=None, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='depot_garantie',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='dernier_montant_loyer',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant du dernier loyer si locataire dans les 18 derniers mois', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='locataire_derniers_18_mois',
            field=models.BooleanField(blank=True, default=None, help_text='Le bien a-t-il eu un locataire dans les 18 derniers mois', null=True),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='montant_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='montant_loyer',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='permis_de_louer',
            field=models.BooleanField(blank=True, default=None, help_text='Indique si un permis de louer est requis pour ce bien', null=True, verbose_name='Permis de louer'),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='premiere_mise_en_location',
            field=models.BooleanField(blank=True, default=None, help_text='Première mise en location du bien', null=True),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='rent_price_id',
            field=models.IntegerField(blank=True, default=None, help_text='ID du RentPrice de référence (base rent_control)', null=True),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='type_charges',
            field=models.CharField(blank=True, choices=[('forfaitaires', 'Forfaitaires'), ('provisionnelles', 'Provisionnelles')], default=None, max_length=20, null=True, verbose_name='Type de charges'),
        ),
        migrations.AlterField(
            model_name='rentterms',
            name='zone_tendue',
            field=models.BooleanField(blank=True, default=None, help_text="Situé en zone d'encadrement des loyers", null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='iban',
            field=models.CharField(blank=True, default=None, max_length=34, null=True),
        ),
    ]
