# Generated by Django 5.1.7 on 2025-11-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_rentterms_honoraires_bail_par_m2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandataire',
            name='date_debut_mandat',
        ),
        migrations.RemoveField(
            model_name='mandataire',
            name='date_fin_mandat',
        ),
    ]
