# Generated by Django 5.1.7 on 2025-09-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_bailleur_personne_alter_bailleur_signataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='chauffage_energie',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='eau_chaude_energie',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
