# Generated by Django 5.1.7 on 2025-09-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_add_null_to_energie_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='identifiant_fiscal',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Identifiant fiscal'),
        ),
    ]
