# Generated by Django 5.1.7 on 2025-11-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_remove_mandataire_date_debut_mandat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='adresse',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
