# Generated by Django 5.1.7 on 2025-11-12 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_alter_personne_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonoraireMandataire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(db_index=True, help_text="Date à partir de laquelle ces tarifs s'appliquent", verbose_name='Date de début de validité')),
                ('date_fin', models.DateField(blank=True, db_index=True, help_text='Laissez vide si tarifs actuellement en vigueur', null=True, verbose_name='Date de fin de validité')),
                ('honoraires_bail_par_m2', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Tarif des honoraires de bail au m² (€/m²). Plafonds légaux : 12€/m² (zone très tendue), 10€/m² (zone tendue), 8€/m² (zone normale).', max_digits=6, null=True, verbose_name='Honoraires bail par m²')),
                ('honoraires_bail_part_bailleur_pct', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Pourcentage des honoraires de bail à la charge du bailleur (0-100%). La part locataire ne peut excéder 50%.', max_digits=5, null=True, verbose_name='Part bailleur bail (%)')),
                ('mandataire_fait_edl', models.BooleanField(default=False, help_text='Indique si le mandataire réalise les états des lieux', verbose_name='Le mandataire fait les EDL')),
                ('honoraires_edl_par_m2', models.DecimalField(blank=True, decimal_places=2, default=None, help_text="Tarif des honoraires d'état des lieux au m² (€/m²). Maximum 3€/m².", max_digits=5, null=True, verbose_name='Honoraires EDL par m²')),
                ('honoraires_edl_part_bailleur_pct', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Pourcentage des honoraires EDL à la charge du bailleur (0-100%). Répartition libre entre bailleur et locataire.', max_digits=5, null=True, verbose_name='Part bailleur EDL (%)')),
                ('raison_changement', models.TextField(blank=True, help_text='Pourquoi ces tarifs ont changé (optionnel)', verbose_name='Raison du changement')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honoraires_mandataire_history', to='location.location')),
            ],
            options={
                'verbose_name': 'Honoraires mandataire',
                'verbose_name_plural': 'Honoraires mandataire',
                'db_table': 'location_honoraires_mandataire',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['location', 'date_debut', 'date_fin'], name='honoraires_location_dates_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gt', models.F('date_debut')), _connector='OR'), name='date_fin_after_date_debut')],
            },
        ),
    ]
