# Generated by Django 5.1.7 on 2025-11-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_honorairemandataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentterms',
            name='honoraires_bail_par_m2',
        ),
        migrations.RemoveField(
            model_name='rentterms',
            name='honoraires_bail_part_bailleur_pct',
        ),
        migrations.RemoveField(
            model_name='rentterms',
            name='honoraires_edl_par_m2',
        ),
        migrations.RemoveField(
            model_name='rentterms',
            name='honoraires_edl_part_bailleur_pct',
        ),
        migrations.RemoveField(
            model_name='rentterms',
            name='mandataire_fait_edl',
        ),
    ]
