# Generated by Django 5.1.7 on 2025-11-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_remove_rentterms_honoraires_bail_par_m2_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='honorairemandataire',
            name='date_fin_after_date_debut',
        ),
        migrations.AddConstraint(
            model_name='honorairemandataire',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('date_fin__gte', models.F('date_debut')), _connector='OR'), name='date_fin_after_date_debut'),
        ),
    ]
