# Generated by Django 5.1.7 on 2025-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_remove_honorairemandataire_date_fin_after_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentterms',
            name='zone_tres_tendue',
            field=models.BooleanField(blank=True, default=None, help_text='Situé en zone très tendue (Zone A bis - arrêté du 1er août 2014)', null=True),
        ),
    ]
