# Generated by Django 5.1.7 on 2025-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_rentterms_zone_tres_tendue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentterms',
            name='zone_tendue_touristique',
            field=models.BooleanField(blank=True, default=None, help_text='Situé en zone tendue touristique (réglementation meublés de tourisme - 120 jours maximum)', null=True),
        ),
    ]
