# Generated by Django 5.1.7 on 2025-11-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_rentterms_zone_tendue_touristique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentterms',
            name='depot_garantie',
        ),
        migrations.AddField(
            model_name='rentterms',
            name='depot_garantie_override',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Override manuel du dépôt de garantie (si None, calculé automatiquement)', max_digits=10, null=True),
        ),
    ]
