# Generated by Django 5.2.8 on 2025-12-06 14:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


def copy_adresse_to_legacy(apps, schema_editor):
    """Copie les anciennes adresses string vers les champs legacy AVANT changement en FK."""
    # Note: À ce stade, adresse est encore un CharField/TextField
    db_alias = schema_editor.connection.alias

    # Pour Bien
    Bien = apps.get_model("location", "Bien")
    for bien in (
        Bien.objects.using(db_alias).exclude(adresse__isnull=True).exclude(adresse="")
    ):
        bien._adresse_legacy = bien.adresse
        bien.save(update_fields=["_adresse_legacy"])

    # Pour Personne
    Personne = apps.get_model("location", "Personne")
    for personne in (
        Personne.objects.using(db_alias)
        .exclude(adresse__isnull=True)
        .exclude(adresse="")
    ):
        personne._adresse_legacy = personne.adresse
        personne.save(update_fields=["_adresse_legacy"])

    # Pour Societe
    Societe = apps.get_model("location", "Societe")
    for societe in (
        Societe.objects.using(db_alias)
        .exclude(adresse__isnull=True)
        .exclude(adresse="")
    ):
        societe._adresse_legacy = societe.adresse
        societe.save(update_fields=["_adresse_legacy"])


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0018_historicalpersonne_historicalsociete"),
    ]

    operations = [
        # 1. Créer le modèle Adresse
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex: 123, 123 bis, 123-125",
                        max_length=20,
                        verbose_name="Numéro",
                    ),
                ),
                (
                    "voie",
                    models.CharField(
                        help_text="Ex: Rue de la Paix, Avenue des Champs-Élysées",
                        max_length=255,
                        verbose_name="Voie",
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex: Bâtiment A, Apt 4B, Étage 3",
                        max_length=255,
                        verbose_name="Complément",
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(max_length=10, verbose_name="Code postal"),
                ),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "pays",
                    models.CharField(
                        default="FR",
                        help_text="Code ISO 3166-1 alpha-2 (ex: FR, BE, CH)",
                        max_length=2,
                        verbose_name="Pays",
                    ),
                ),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "Adresse",
                "verbose_name_plural": "Adresses",
            },
        ),
        # 2. Ajouter les champs legacy
        migrations.AddField(
            model_name="bien",
            name="_adresse_legacy",
            field=models.CharField(
                blank=True,
                db_column="adresse_legacy",
                default=None,
                help_text="DEPRECATED: Ancienne adresse texte, à migrer vers FK Adresse",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="_adresse_legacy",
            field=models.CharField(
                blank=True,
                db_column="adresse_legacy",
                default=None,
                help_text="DEPRECATED: Ancienne adresse texte, à migrer vers FK Adresse",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonne",
            name="_adresse_legacy",
            field=models.TextField(
                blank=True, db_column="adresse_legacy", default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalsociete",
            name="_adresse_legacy",
            field=models.TextField(
                blank=True, db_column="adresse_legacy", default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="personne",
            name="_adresse_legacy",
            field=models.TextField(
                blank=True, db_column="adresse_legacy", default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="societe",
            name="_adresse_legacy",
            field=models.TextField(
                blank=True, db_column="adresse_legacy", default=None, null=True
            ),
        ),
        # 3. COPIER les anciennes adresses vers legacy AVANT suppression
        migrations.RunPython(copy_adresse_to_legacy, migrations.RunPython.noop),
        # 4. SUPPRIMER les anciens champs adresse (texte) - impossible de convertir texte → UUID
        migrations.RemoveField(model_name="bien", name="adresse"),
        migrations.RemoveField(model_name="historicalbien", name="adresse"),
        migrations.RemoveField(model_name="historicalpersonne", name="adresse"),
        migrations.RemoveField(model_name="historicalsociete", name="adresse"),
        migrations.RemoveField(model_name="personne", name="adresse"),
        migrations.RemoveField(model_name="societe", name="adresse"),
        # 5. AJOUTER les nouveaux champs adresse comme FK vers Adresse
        migrations.AddField(
            model_name="bien",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="biens",
                to="location.adresse",
                verbose_name="Adresse",
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.adresse",
                verbose_name="Adresse",
            ),
        ),
        migrations.AddField(
            model_name="historicalpersonne",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Adresse structurée de la personne",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.adresse",
            ),
        ),
        migrations.AddField(
            model_name="historicalsociete",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Adresse du siège social",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.adresse",
            ),
        ),
        migrations.AddField(
            model_name="personne",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                help_text="Adresse structurée de la personne",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnes",
                to="location.adresse",
            ),
        ),
        migrations.AddField(
            model_name="societe",
            name="adresse",
            field=models.ForeignKey(
                blank=True,
                help_text="Adresse du siège social",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="societes",
                to="location.adresse",
            ),
        ),
    ]
