# Generated by Django 5.2.8 on 2025-12-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_adresse_bien__adresse_legacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='code_postal',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='complement',
            field=models.CharField(blank=True, default=None, help_text='Ex: Bâtiment A, Apt 4B, Étage 3', max_length=255, null=True, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='numero',
            field=models.CharField(blank=True, default=None, help_text='Ex: 123, 123 bis, 123-125', max_length=20, null=True, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='voie',
            field=models.CharField(blank=True, default=None, help_text='Ex: Rue de la Paix, Avenue des Champs-Élysées', max_length=255, null=True, verbose_name='Voie'),
        ),
    ]
