# Generated by Django 5.2.8 on 2025-12-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_alter_adresse_code_postal_alter_adresse_complement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='historicalbien',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='historicalbien',
            name='longitude',
        ),
    ]
