# Generated by Django 5.2.8 on 2025-12-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_remove_bien_latitude_remove_bien_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='_adresse_legacy',
        ),
        migrations.RemoveField(
            model_name='historicalbien',
            name='_adresse_legacy',
        ),
        migrations.RemoveField(
            model_name='historicalpersonne',
            name='_adresse_legacy',
        ),
        migrations.RemoveField(
            model_name='historicalsociete',
            name='_adresse_legacy',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='_adresse_legacy',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='_adresse_legacy',
        ),
    ]
