# Generated by Django 5.2.8 on 2025-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_etage_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='has_piece_over_50m2',
            field=models.BooleanField(blank=True, default=None, help_text='Indique si le logement possède une pièce de plus de 50m² (exclusion MRH)', null=True, verbose_name='A une pièce de plus de 50m²'),
        ),
        migrations.AddField(
            model_name='historicalbien',
            name='has_piece_over_50m2',
            field=models.BooleanField(blank=True, default=None, help_text='Indique si le logement possède une pièce de plus de 50m² (exclusion MRH)', null=True, verbose_name='A une pièce de plus de 50m²'),
        ),
    ]
