# Generated by Django 5.1.7 on 2025-03-25 15:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentControlZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('IDF', 'Île-de-France'), ('PAYS_BASQUE', 'Pays Basque'), ('LYON', 'Lyon'), ('MONTPELLIER', 'Montpellier'), ('BORDEAUX', 'Bordeaux')], max_length=20)),
                ('zone', models.CharField(max_length=50)),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('apartment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('room_count', models.CharField(blank=True, max_length=20, null=True)),
                ('construction_period', models.CharField(blank=True, max_length=50, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['region'], name='rent_contro_region_0c0e6f_idx')],
            },
        ),
    ]
