# Generated by Django 5.1.7 on 2025-03-28 20:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentControlArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('PARIS', 'Paris'), ('EST_ENSEMBLE', 'Est Ensemble'), ('PLAINE_COMMUNE', 'Plaine Commune'), ('PAYS_BASQUE', 'Pays Basque'), ('LYON', 'Lyon'), ('MONTPELLIER', 'Montpellier'), ('BORDEAUX', 'Bordeaux'), ('LILLE', 'Lille')], max_length=20)),
                ('reference_year', models.IntegerField()),
                ('zone_id', models.CharField(max_length=20)),
                ('zone_name', models.CharField(blank=True, max_length=50, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'indexes': [models.Index(fields=['region', 'zone_id', 'reference_year'], name='rent_contro_region_46297b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison')], max_length=20)),
                ('room_count', models.CharField(choices=[('1', '1 pièce'), ('2', '2 pièces'), ('3', '3 pièces'), ('4', '4 pièces et plus')], max_length=10)),
                ('construction_period', models.CharField(choices=[('avant 1946', 'Avant 1946'), ('1946-1970', '1946-1970'), ('1971-1990', '1971-1990'), ('apres 1990', 'Après 1990')], max_length=20)),
                ('furnished', models.BooleanField()),
                ('reference_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='rent_control.rentcontrolarea')),
            ],
            options={
                'indexes': [models.Index(fields=['property_type', 'room_count', 'furnished', 'construction_period'], name='rent_contro_propert_64369a_idx')],
                'constraints': [models.UniqueConstraint(fields=('area', 'property_type', 'room_count', 'construction_period', 'furnished'), name='unique_property_characteristics')],
            },
        ),
    ]
