# Generated by Django 5.1.7 on 2025-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneTendue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agglomerations', models.CharField(blank=True, max_length=255, null=True, verbose_name="Agglomérations (unités urbaines au sens de l'INSEE)")),
                ('departements', models.CharField(max_length=255, verbose_name='Départements')),
                ('communes', models.CharField(max_length=255, verbose_name='Communes')),
                ('code_insee', models.CharField(db_index=True, max_length=10, verbose_name='Code INSEE')),
            ],
            options={
                'verbose_name': 'Zone tendue',
                'verbose_name_plural': 'Zones tendues',
                'indexes': [models.Index(fields=['code_insee'], name='rent_contro_code_in_0f7cab_idx')],
            },
        ),
    ]
