# Generated by Django 5.1.7 on 2025-04-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentMap',
            fields=[
            ],
            options={
                'verbose_name': 'Carte des zones',
                'verbose_name_plural': 'Carte des zones',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rent_control.rentcontrolarea',),
        ),
    ]
