# Generated by Django 5.1.7 on 2025-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcontrolzone',
            name='reference_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
