# Generated by Django 5.1.7 on 2025-07-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_control', '0002_zonetendue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisDeLouer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField(verbose_name='Raw data')),
                ('villes', models.CharField(max_length=255, verbose_name='Villes')),
                ('specificite_par_quartier', models.BooleanField(default=False, verbose_name='Spécificités par Quartier')),
                ('date_inconnues', models.BooleanField(default=False, verbose_name='Date inconnue')),
            ],
            options={
                'verbose_name': 'Permis de louer',
                'verbose_name_plural': 'Permis de louer',
                'indexes': [models.Index(fields=['villes'], name='rent_contro_villes_857e79_idx')],
            },
        ),
    ]
