# Generated by Django 5.1.7 on 2025-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_control', '0003_permisdelouer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneTresTendue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement_code', models.CharField(max_length=3, verbose_name='Code département')),
                ('departement_nom', models.CharField(max_length=100, verbose_name='Département')),
                ('commune', models.CharField(max_length=255, verbose_name='Commune')),
            ],
            options={
                'verbose_name': 'Zone très tendue (A bis)',
                'verbose_name_plural': 'Zones très tendues (A bis)',
                'indexes': [models.Index(fields=['departement_code', 'commune'], name='rent_contro_departe_2015b9_idx'), models.Index(fields=['commune'], name='rent_contro_commune_9cee81_idx')],
            },
        ),
    ]
