# Generated by Django 5.1.7 on 2025-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_control', '0003_alter_rentcontrolarea_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentprice',
            name='construction_period',
            field=models.CharField(choices=[('avant 1946', 'Avant 1946'), ('1946-1970', '1946-1970'), ('1971-1990', '1971-1990'), ('1990-2005', '1990-2005'), ('apres 1990', 'Après 1990'), ('apres 2005', 'Après 2005')], max_length=20),
        ),
    ]
