# Generated by Django 5.1.7 on 2025-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_control', '0004_zonetrestendue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneTendueTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement_code', models.CharField(max_length=3, verbose_name='Code département')),
                ('commune', models.CharField(max_length=255, verbose_name='Commune')),
                ('code_insee', models.CharField(db_index=True, max_length=10, verbose_name='Code INSEE')),
            ],
            options={
                'verbose_name': 'Zone tendue touristique',
                'verbose_name_plural': 'Zones tendues touristiques',
                'indexes': [models.Index(fields=['code_insee'], name='rent_contro_code_in_242ec9_idx'), models.Index(fields=['departement_code', 'commune'], name='rent_contro_departe_ee6e84_idx'), models.Index(fields=['commune'], name='rent_contro_commune_3fb5b7_idx')],
            },
        ),
    ]
