# Generated by Django 5.2.8 on 2025-12-10 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0023_etage_to_integer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', help_text='Statut de signature du document', max_length=20, verbose_name='Statut du document')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Document PDF')),
                ('latest_pdf', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Dernière version signée')),
                ('product', models.CharField(choices=[('MRH', 'Multirisque Habitation (Locataire)'), ('PNO', 'Propriétaire Non Occupant'), ('GLI', 'Garantie Loyers Impayés')], default='MRH', max_length=10)),
                ('deductible', models.IntegerField(default=170)),
                ('effective_date', models.DateField()),
                ('formulas_data', models.JSONField()),
                ('selected_formula_code', models.CharField(blank=True, default='', max_length=50)),
                ('devis_document', models.FileField(blank=True, default=None, null=True, upload_to='assurances/devis/')),
                ('expires_at', models.DateTimeField()),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_quotations', to='location.location')),
                ('user', models.ForeignKey(help_text='Utilisateur ayant demandé le devis', on_delete=django.db.models.deletion.CASCADE, related_name='insurance_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis assurance',
                'verbose_name_plural': 'Devis assurances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(blank=True, help_text='Format: PO-{PRODUCT}IND-67XXXXXXX', max_length=25, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('ACTIVE', 'Active'), ('CANCELLED', 'Résiliée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=20)),
                ('end_date', models.DateField(blank=True, default=None, help_text='Date de fin (null = en cours)', null=True)),
                ('activated_at', models.DateTimeField(blank=True, default=None, help_text="Date d'activation après paiement", null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', help_text='ID de la Checkout Session Stripe', max_length=100)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', help_text='ID du PaymentIntent Stripe (paiement unique)', max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', help_text='ID de la Subscription Stripe (paiement mensuel)', max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, default='', help_text='ID du Customer Stripe', max_length=100)),
                ('attestation_document', models.FileField(blank=True, default=None, help_text="Attestation d'assurance PDF", null=True, upload_to='assurances/attestation/')),
                ('subscriber', models.ForeignKey(help_text='Souscripteur (locataire ou bailleur)', on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(help_text='Devis source (contient product, location, formule, tarifs)', on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='assurances.insurancequotation')),
            ],
            options={
                'verbose_name': 'Police assurance',
                'verbose_name_plural': 'Polices assurances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceQuotationSignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Ordre de signature dans le processus')),
                ('otp', models.CharField(blank=True, default='', max_length=6)),
                ('otp_generated_at', models.DateTimeField(blank=True, help_text="Horodatage de génération de l'OTP (pour vérifier l'expiration)", null=True)),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text="Date d'annulation de la demande de signature", null=True)),
                ('bailleur_signataire', models.ForeignKey(blank=True, help_text='Signataire du bailleur (personne physique ou représentant de société)', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.personne')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant annulé la demande de signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL)),
                ('locataire', models.ForeignKey(blank=True, help_text='Locataire souscripteur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_signature_requests', to='location.locataire')),
                ('mandataire', models.ForeignKey(blank=True, help_text='Mandataire qui signe pour le compte du bailleur', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.mandataire')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='assurances.insurancequotation')),
            ],
            options={
                'verbose_name': 'Demande signature assurance',
                'verbose_name_plural': 'Demandes signatures assurances',
            },
        ),
        migrations.AddIndex(
            model_name='insurancequotation',
            index=models.Index(fields=['user', 'product', 'status'], name='assurances__user_id_002be0_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancequotation',
            index=models.Index(fields=['expires_at'], name='assurances__expires_317388_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancequotation',
            index=models.Index(fields=['status'], name='assurances__status_ee55e3_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_number'], name='assurances__policy__10885a_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['subscriber', 'status'], name='assurances__subscri_1abb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['status'], name='assurances__status_05931f_idx'),
        ),
        migrations.AddConstraint(
            model_name='insurancequotationsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('quotation', 'locataire'), name='unique_quotation_locataire_active'),
        ),
    ]
