# Generated by Django 5.2.8 on 2025-12-11 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('DER', "Document d'Entrée en Relation"), ('CGV_MRH', 'Conditions Générales MRH'), ('CGV_PNO', 'Conditions Générales PNO'), ('CGV_GLI', 'Conditions Générales GLI')], help_text='Type de document statique', max_length=20, unique=True)),
                ('file', models.FileField(help_text='Fichier PDF généré', upload_to='assurances/static_documents/')),
                ('version', models.CharField(default='1.0', help_text='Version du document (ex: 2024.1)', max_length=20)),
            ],
            options={
                'verbose_name': 'Document statique',
                'verbose_name_plural': 'Documents statiques',
            },
        ),
    ]
