# Generated by Django 5.2.8 on 2025-12-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0002_staticdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspendue (impayé)'), ('CANCELLED', 'Résiliée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=20),
        ),
    ]
