# Generated by Django 5.1.7 on 2025-10-02 09:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Document PDF')),
                ('latest_pdf', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Dernière version signée')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé')], default='draft', max_length=20)),
                ('duree_mois', models.IntegerField(default=12)),
                ('justificatifs', models.JSONField(default=list)),
                ('clauses_particulieres', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('notice_information_pdf', models.FileField(blank=True, null=True, upload_to='bail_pdfs/')),
                ('dpe_pdf', models.FileField(blank=True, null=True, upload_to='bail_pdfs/', verbose_name='Diagnostic de Performance Énergétique PDF')),
                ('grille_vetuste_pdf', models.FileField(blank=True, null=True, upload_to='bail_pdfs/', verbose_name='Grille de vétusté PDF')),
                ('date_signature', models.DateField(default=django.utils.timezone.now)),
                ('travaux_bailleur', models.TextField(blank=True)),
                ('travaux_locataire', models.TextField(blank=True)),
                ('honoraires_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bail', to='location.location')),
            ],
            options={
                'verbose_name': 'Bail',
                'verbose_name_plural': 'Bails',
                'db_table': 'bail_bail_new',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='BailSignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Ordre de signature dans le processus')),
                ('otp', models.CharField(blank=True, default='', max_length=6)),
                ('otp_generated_at', models.DateTimeField(blank=True, help_text="Horodatage de génération de l'OTP (pour vérifier l'expiration)", null=True)),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='bail.bail')),
                ('bailleur_signataire', models.ForeignKey(blank=True, help_text='Signataire du bailleur (personne physique ou représentant de société)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bailleur_signature_requests', to='location.personne')),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bail_signature_requests', to='location.locataire')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('bail', 'Contrat de bail'), ('grille_vetuste', 'Grille de vétusté'), ('notice_information', "Notice d'information"), ('diagnostic', 'Diagnostic'), ('permis_de_louer', 'Permis de louer'), ('autre', 'Autre document')], max_length=50)),
                ('nom_original', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('bail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bail.bail')),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='location.bien')),
                ('uploade_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'bail_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('location',), name='unique_active_bail_per_location'),
        ),
        migrations.AlterUniqueTogether(
            name='bailsignaturerequest',
            unique_together={('bail', 'bailleur_signataire'), ('bail', 'locataire')},
        ),
    ]
