# Generated by Django 5.1.7 on 2025-04-04 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison')], max_length=20, verbose_name='Type de bien')),
                ('adresse', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('superficie', models.DecimalField(decimal_places=2, help_text='En m²', max_digits=8)),
                ('nb_pieces', models.CharField(choices=[('1', '1 pièce'), ('2', '2 pièces'), ('3', '3 pièces'), ('4', '4 pièces et plus')], max_length=10, verbose_name='Nombre de pièces')),
                ('etage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('periode_construction', models.CharField(blank=True, choices=[('avant 1946', 'Avant 1946'), ('1946-1970', '1946-1970'), ('1971-1990', '1971-1990'), ('1990-2005', '1990-2005'), ('apres 1990', 'Après 1990'), ('apres 2005', 'Après 2005')], max_length=20, null=True, verbose_name='Période de construction')),
                ('meuble', models.BooleanField(default=False, verbose_name='Meublé')),
                ('annexes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('adresse_actuelle', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('employeur', models.CharField(blank=True, max_length=100)),
                ('revenu_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_carte_identite', models.CharField(blank=True, max_length=30)),
                ('date_emission_ci', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BailSpecificites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jour_paiement', models.PositiveSmallIntegerField(default=5, help_text='Jour du mois')),
                ('depot_garantie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('releve_eau_entree', models.CharField(blank=True, max_length=20)),
                ('releve_elec_entree', models.CharField(blank=True, max_length=20)),
                ('releve_gaz_entree', models.CharField(blank=True, max_length=20)),
                ('date_signature', models.DateField(default=django.utils.timezone.now)),
                ('date_etat_lieux_entree', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('zone_tendue', models.BooleanField(default=False, help_text="Situé en zone d'encadrement des loyers")),
                ('prix_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('complement_loyer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bails', to='bail.bien')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bails', to='bail.locataire')),
            ],
        ),
        migrations.AddField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='bail.proprietaire'),
        ),
    ]
