# Generated by Django 5.1.7 on 2025-08-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailspecificites',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='permis_de_louer',
            field=models.BooleanField(default=False, help_text='Indique si un permis de louer est requis pour ce bien', verbose_name='Permis de louer'),
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing_in_progress', 'En cours de signature'), ('signed', 'Signé et finalisé')], default='draft', help_text='Statut actuel du bail dans son cycle de vie', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('bail', 'Contrat de bail'), ('grille_vetuste', 'Grille de vétusté'), ('notice_information', "Notice d'information"), ('diagnostic', 'Diagnostic'), ('permis_de_louer', 'Permis de louer'), ('autre', 'Autre document')], help_text='Type de document', max_length=50),
        ),
    ]
