# Generated by Django 5.1.7 on 2025-10-03 21:53

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0001_initial'),
        ('location', '0002_historicalbien_historicallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Document PDF')),
                ('latest_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dernière version signée')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('duree_mois', models.IntegerField(default=12)),
                ('justificatifs', models.JSONField(default=list)),
                ('clauses_particulieres', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('notice_information_pdf', models.TextField(blank=True, max_length=100, null=True)),
                ('dpe_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Diagnostic de Performance Énergétique PDF')),
                ('grille_vetuste_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Grille de vétusté PDF')),
                ('date_signature', models.DateField(default=django.utils.timezone.now)),
                ('travaux_bailleur', models.TextField(blank=True)),
                ('travaux_locataire', models.TextField(blank=True)),
                ('honoraires_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Bail',
                'verbose_name_plural': 'historical Bails',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='bail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bail', 'verbose_name_plural': 'Bails'},
        ),
        migrations.RemoveConstraint(
            model_name='bail',
            name='unique_active_bail_per_location',
        ),
        migrations.RemoveField(
            model_name='bail',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bail',
            name='version',
        ),
        migrations.AddField(
            model_name='bail',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bails', to='location.location'),
        ),
        migrations.AlterField(
            model_name='bail',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bail',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SIGNING', 'SIGNED'])), fields=('location',), name='unique_signing_or_signed_bail_per_location'),
        ),
        migrations.AddField(
            model_name='historicalbail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbail',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location'),
        ),
    ]
