# Generated by Django 5.1.7 on 2025-06-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='siret',
            field=models.CharField(max_length=14),
        ),
    ]
