# Generated by Django 5.1.7 on 2025-09-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0001_initial'),
        ('location', '0011_add_null_to_identifiant_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bail',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bail', to='location.location'),
        ),
        migrations.AlterField(
            model_name='bail',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé')], default='draft', max_length=20),
        ),
    ]
