# Generated by Django 5.1.7 on 2025-04-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bien',
            old_name='description',
            new_name='additionnal_description',
        ),
        migrations.AddField(
            model_name='bien',
            name='classe_dpe',
            field=models.CharField(choices=[('A', 'A (≤ 70 kWh/m²/an)'), ('B', 'B (71 à 110 kWh/m²/an)'), ('C', 'C (111 à 180 kWh/m²/an)'), ('D', 'D (181 à 250 kWh/m²/an)'), ('E', 'E (251 à 330 kWh/m²/an)'), ('F', 'F (331 à 420 kWh/m²/an)'), ('G', 'G (> 420 kWh/m²/an)'), ('NC', 'Non communiqué')], default='NC', max_length=2, verbose_name='Classe énergétique DPE'),
        ),
        migrations.AddField(
            model_name='bien',
            name='depenses_energetiques',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dépenses énergétiques théoriques (€/an)'),
        ),
        migrations.AddField(
            model_name='bien',
            name='dernier_etage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bien',
            name='porte',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='adresse_actuelle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='locataire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
