# Generated by Django 5.1.7 on 2025-07-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailspecificites',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing_in_progress', 'En cours de signature'), ('signed', 'Signé et finalisé')], default='draft', help_text='Statut actuel du bail dans son cycle de vie', max_length=20, verbose_name='Statut'),
        ),
    ]
