# Generated by Django 5.1.7 on 2025-04-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0002_rename_description_bien_additionnal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailspecificites',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='bail_pdfs/', verbose_name='Bail PDF'),
        ),
    ]
