# Generated by Django 5.1.7 on 2025-08-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bail", "0002_remove_bailspecificites_is_draft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailsignaturerequest",
            name="otp_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Horodatage de génération de l'OTP (pour vérifier l'expiration)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bailsignaturerequest",
            name="otp",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
    ]
