# Generated by Django 5.1.7 on 2025-10-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0002_historicalbail_alter_bail_options_and_more'),
        ('location', '0003_locataire_attestation_mrh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='locataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='location.locataire'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('bail', 'Contrat de bail'), ('grille_vetuste', 'Grille de vétusté'), ('notice_information', "Notice d'information"), ('diagnostic', 'Diagnostic'), ('permis_de_louer', 'Permis de louer'), ('attestation_mrh', 'Attestation MRH'), ('caution_solidaire', 'Caution solidaire'), ('autre', 'Autre document')], max_length=50),
        ),
    ]
