# Generated by Django 5.1.7 on 2025-07-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0002_remove_bailspecificites_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailspecificites',
            name='permis_de_louer',
            field=models.BooleanField(default=False, help_text='Indique si un permis de louer est requis pour ce bien', verbose_name='Permis de louer'),
        ),
    ]
