# Generated by Django 5.1.7 on 2025-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0003_bailspecificites_permis_de_louer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('bail', 'Contrat de bail'), ('grille_vetuste', 'Grille de vétusté'), ('notice_information', "Notice d'information"), ('diagnostic', 'Diagnostic'), ('permis_de_louer', 'Permis de louer'), ('autre', 'Autre document')], help_text='Type de document', max_length=50),
        ),
    ]
