# Generated by Django 5.1.7 on 2025-11-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0003_add_locataire_to_document'),
        ('location', '0011_alter_personne_adresse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bailsignaturerequest',
            unique_together={('bail', 'bailleur_signataire'), ('bail', 'locataire')},
        ),
        migrations.AddField(
            model_name='bailsignaturerequest',
            name='mandataire',
            field=models.ForeignKey(blank=True, help_text='Mandataire qui signe pour le compte du bailleur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bail_signature_requests', to='location.mandataire'),
        ),
        migrations.AlterUniqueTogether(
            name='bailsignaturerequest',
            unique_together={('bail', 'bailleur_signataire'), ('bail', 'locataire'), ('bail', 'mandataire')},
        ),
    ]
