# Generated by Django 5.1.7 on 2025-08-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0003_bailsignaturerequest_otp_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailsignaturerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bailsignaturerequest',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='bailsignaturerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bailsignaturerequest',
            name='locataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bail_signature_requests', to='bail.locataire'),
        ),
    ]
