# Generated by Django 5.1.7 on 2025-04-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0003_bailspecificites_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailspecificites',
            name='locataire',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='proprietaire',
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='locataires',
            field=models.ManyToManyField(related_name='bails', to='bail.locataire'),
        ),
        migrations.AddField(
            model_name='bien',
            name='proprietaires',
            field=models.ManyToManyField(related_name='biens', to='bail.proprietaire'),
        ),
    ]
