# Generated by Django 5.1.7 on 2025-04-18 14:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bail", "0004_remove_bailspecificites_locataire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailspecificites",
            name="latest_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="bail_pdfs/",
                verbose_name="Dernière version signée",
            ),
        ),
        migrations.CreateModel(
            name="BailSignatureRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="Ordre de signature dans le processus"
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "link_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "bail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_requests",
                        to="bail.bailspecificites",
                    ),
                ),
                (
                    "locataire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_requests",
                        to="bail.locataire",
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_requests",
                        to="bail.proprietaire",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("bail", "locataire"), ("bail", "proprietaire")},
            },
        ),
    ]
