# Generated by Django 5.1.7 on 2025-11-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0004_alter_bailsignaturerequest_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bail',
            name='date_signature',
        ),
        migrations.RemoveField(
            model_name='historicalbail',
            name='date_signature',
        ),
        migrations.AddField(
            model_name='bail',
            name='mandataire_doit_signer',
            field=models.BooleanField(default=False, help_text='Si True : le mandataire est signataire juridique du document et sera inclus dans les demandes de signature', verbose_name='Le mandataire signe ce document'),
        ),
        migrations.AddField(
            model_name='historicalbail',
            name='mandataire_doit_signer',
            field=models.BooleanField(default=False, help_text='Si True : le mandataire est signataire juridique du document et sera inclus dans les demandes de signature', verbose_name='Le mandataire signe ce document'),
        ),
        migrations.AlterField(
            model_name='bail',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', help_text='Statut de signature du document', max_length=20, verbose_name='Statut du document'),
        ),
        migrations.AlterField(
            model_name='historicalbail',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', help_text='Statut de signature du document', max_length=20, verbose_name='Statut du document'),
        ),
    ]
