# Generated by Django 5.1.7 on 2025-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0005_remove_bail_date_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bail',
            name='grille_vetuste_pdf',
        ),
        migrations.RemoveField(
            model_name='bail',
            name='notice_information_pdf',
        ),
        migrations.RemoveField(
            model_name='historicalbail',
            name='grille_vetuste_pdf',
        ),
        migrations.RemoveField(
            model_name='historicalbail',
            name='notice_information_pdf',
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('bail', 'Contrat de bail'), ('grille_vetuste', 'Grille de vétusté'), ('notice_information', "Notice d'information"), ('diagnostic', 'Diagnostics techniques'), ('permis_de_louer', 'Permis de louer'), ('attestation_mrh', 'Attestation MRH'), ('caution_solidaire', 'Caution solidaire'), ('autre', 'Autre document')], max_length=50),
        ),
    ]
