# Generated by Django 5.1.7 on 2025-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0005_alter_bailspecificites_latest_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailspecificites',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
