# Generated by Django 5.1.7 on 2025-06-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0005_bailspecificites_latest_pdf_bailsignaturerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailspecificites',
            name='dpe_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bail_pdfs/', verbose_name='Diagnostic de Performance Énergétique PDF'),
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='grille_vetuste_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bail_pdfs/', verbose_name='Grille de vétusté PDF'),
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='Indique si le bail est encore en mode brouillon', verbose_name='Brouillon'),
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='notice_information_pdf',
            field=models.FileField(blank=True, null=True, upload_to='bail_pdfs/', verbose_name="Notice d'information PDF"),
        ),
    ]
