# Generated by Django 5.1.7 on 2025-11-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0006_remove_bail_grille_vetuste_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bail',
            name='dpe_pdf',
        ),
        migrations.RemoveField(
            model_name='historicalbail',
            name='dpe_pdf',
        ),
    ]
