# Generated by Django 5.1.7 on 2025-06-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0006_bailspecificites_dpe_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='annexes_collectives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bien',
            name='annexes_privatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bien',
            name='chauffage_energie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bien',
            name='chauffage_type',
            field=models.CharField(blank=True, choices=[('collectif', 'Collectif'), ('individuel', 'Individuel')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='eau_chaude_energie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bien',
            name='eau_chaude_type',
            field=models.CharField(blank=True, choices=[('collectif', 'Collectif'), ('individuel', 'Individuel')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='equipements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
