# Generated by Django 5.1.7 on 2025-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0007_bien_annexes_collectives_bien_annexes_privatives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='pieces_info',
            field=models.JSONField(blank=True, default=dict, help_text='Détail des pièces: chambres, sallesDeBain, cuisines, etc.'),
        ),
    ]
