# Generated by Django 5.1.7 on 2025-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0007_remove_bail_dpe_pdf_remove_historicalbail_dpe_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='bail',
            name='signature_dpe_g_acknowledgment',
            field=models.BooleanField(default=False, help_text="Confirmation du bailleur qu'il assume la responsabilité de louer un logement classé G, non décent depuis le 1er janvier 2025", verbose_name='Confirmation responsabilité DPE G'),
        ),
        migrations.AddField(
            model_name='historicalbail',
            name='signature_dpe_g_acknowledgment',
            field=models.BooleanField(default=False, help_text="Confirmation du bailleur qu'il assume la responsabilité de louer un logement classé G, non décent depuis le 1er janvier 2025", verbose_name='Confirmation responsabilité DPE G'),
        ),
    ]
