# Generated by Django 5.1.7 on 2025-11-26 09:23

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0008_bail_signature_dpe_g_acknowledgment_and_more'),
        ('location', '0018_historicalpersonne_historicalsociete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('bail', 'Contrat de bail'), ('avenant', 'Avenant au bail'), ('grille_vetuste', 'Grille de vétusté'), ('notice_information', "Notice d'information"), ('diagnostic', 'Diagnostics techniques'), ('permis_de_louer', 'Permis de louer'), ('attestation_mrh', 'Attestation MRH'), ('caution_solidaire', 'Caution solidaire'), ('autre', 'Autre document')], max_length=50),
        ),
        migrations.CreateModel(
            name='Avenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', help_text='Statut de signature du document', max_length=20, verbose_name='Statut du document')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Document PDF')),
                ('latest_pdf', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Dernière version signée')),
                ('numero', models.PositiveIntegerField(help_text="Numéro séquentiel de l'avenant pour ce bail", verbose_name="Numéro d'avenant")),
                ('motifs', models.JSONField(default=list, help_text='Liste des motifs : identifiant_fiscal, diagnostics_ddt, permis_de_louer', verbose_name="Motifs de l'avenant")),
                ('identifiant_fiscal', models.CharField(blank=True, default=None, help_text="Numéro d'identifiant fiscal du logement (si ajouté via cet avenant)", max_length=50, null=True, verbose_name='Identifiant fiscal ajouté')),
                ('bail', models.ForeignKey(help_text='Bail auquel cet avenant est rattaché', on_delete=django.db.models.deletion.CASCADE, related_name='avenants', to='bail.bail')),
            ],
            options={
                'verbose_name': 'Avenant',
                'verbose_name_plural': 'Avenants',
                'db_table': 'bail_avenant',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvenantSignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Ordre de signature dans le processus')),
                ('otp', models.CharField(blank=True, default='', max_length=6)),
                ('otp_generated_at', models.DateTimeField(blank=True, help_text="Horodatage de génération de l'OTP (pour vérifier l'expiration)", null=True)),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('avenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='bail.avenant')),
                ('bailleur_signataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avenant_bailleur_signature_requests', to='location.personne')),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avenant_signature_requests', to='location.locataire')),
                ('mandataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avenant_signature_requests', to='location.mandataire')),
            ],
            options={
                'db_table': 'bail_avenant_signature_request',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAvenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', help_text='Statut de signature du document', max_length=20, verbose_name='Statut du document')),
                ('pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Document PDF')),
                ('latest_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dernière version signée')),
                ('numero', models.PositiveIntegerField(help_text="Numéro séquentiel de l'avenant pour ce bail", verbose_name="Numéro d'avenant")),
                ('motifs', models.JSONField(default=list, help_text='Liste des motifs : identifiant_fiscal, diagnostics_ddt, permis_de_louer', verbose_name="Motifs de l'avenant")),
                ('identifiant_fiscal', models.CharField(blank=True, default=None, help_text="Numéro d'identifiant fiscal du logement (si ajouté via cet avenant)", max_length=50, null=True, verbose_name='Identifiant fiscal ajouté')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bail', models.ForeignKey(blank=True, db_constraint=False, help_text='Bail auquel cet avenant est rattaché', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bail.bail')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Avenant',
                'verbose_name_plural': 'historical Avenants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='avenant',
            constraint=models.UniqueConstraint(fields=('bail', 'numero'), name='unique_avenant_numero_per_bail'),
        ),
        migrations.AlterUniqueTogether(
            name='avenantsignaturerequest',
            unique_together={('avenant', 'bailleur_signataire'), ('avenant', 'locataire'), ('avenant', 'mandataire')},
        ),
    ]
