# Generated by Django 5.1.7 on 2025-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0008_add_pieces_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='identifiant_fiscal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Identifiant fiscal'),
        ),
    ]
