# Generated by Django 5.1.7 on 2025-11-26 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0009_alter_document_type_document_avenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='avenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bail.avenant'),
        ),
    ]
