# Generated by Django 5.1.7 on 2025-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0009_bien_identifiant_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='regime_juridique',
            field=models.CharField(choices=[('monopropriete', 'Monopropriété'), ('copropriete', 'Copropriété')], default='monopropriete', max_length=20, verbose_name='Régime juridique'),
        ),
    ]
