# Generated by Django 5.1.7 on 2025-06-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0010_bien_regime_juridique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bien',
            old_name='equipements',
            new_name='information',
        ),
    ]
