# Generated by Django 5.1.7 on 2025-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0011_rename_equipements_bien_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='classe_dpe',
            field=models.CharField(choices=[('A', 'A (≤ 70 kWh/m²/an)'), ('B', 'B (71 à 110 kWh/m²/an)'), ('C', 'C (111 à 180 kWh/m²/an)'), ('D', 'D (181 à 250 kWh/m²/an)'), ('E', 'E (251 à 330 kWh/m²/an)'), ('F', 'F (331 à 420 kWh/m²/an)'), ('G', 'G (> 420 kWh/m²/an)'), ('NA', 'Non soumis à DPE')], default='NA', max_length=2, verbose_name='Classe énergétique DPE'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='depenses_energetiques',
            field=models.CharField(blank=True, default='non renseigné', max_length=400, verbose_name='Dépenses énergétiques théoriques (€/an)'),
        ),
    ]
