# Generated by Django 5.2.8 on 2025-12-05 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0011_avenantsignaturerequest_cancelled_at_and_more'),
        ('location', '0018_historicalpersonne_historicalsociete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avenantsignaturerequest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bailsignaturerequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='avenantsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('avenant', 'bailleur_signataire'), name='unique_avenant_bailleur_signataire_active'),
        ),
        migrations.AddConstraint(
            model_name='avenantsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('avenant', 'locataire'), name='unique_avenant_locataire_active'),
        ),
        migrations.AddConstraint(
            model_name='avenantsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('avenant', 'mandataire'), name='unique_avenant_mandataire_active'),
        ),
        migrations.AddConstraint(
            model_name='bailsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('bail', 'bailleur_signataire'), name='unique_bail_bailleur_signataire_active'),
        ),
        migrations.AddConstraint(
            model_name='bailsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('bail', 'locataire'), name='unique_bail_locataire_active'),
        ),
        migrations.AddConstraint(
            model_name='bailsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('bail', 'mandataire'), name='unique_bail_mandataire_active'),
        ),
    ]
