# Generated by Django 5.2.8 on 2025-12-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0012_alter_avenantsignaturerequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('bail', 'Contrat de bail'), ('avenant', 'Avenant au bail'), ('grille_vetuste', 'Grille de vétusté'), ('notice_information', "Notice d'information"), ('diagnostic', 'Diagnostics techniques'), ('permis_de_louer', 'Permis de louer'), ('attestation_mrh', 'Attestation MRH'), ('caution_solidaire', 'Caution solidaire'), ('carte_identite', "Carte d'identité"), ('autre', 'Autre document')], max_length=50),
        ),
    ]
