# Generated by Django 5.1.7 on 2025-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0012_alter_bien_classe_dpe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailspecificites',
            name='solidaires',
            field=models.BooleanField(default=False, help_text='Indique si les locataires sont solidaires pour le paiement du loyer'),
        ),
    ]
