# Generated by Django 5.1.7 on 2025-06-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0013_bailspecificites_solidaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailspecificites',
            name='type_charges',
            field=models.CharField(choices=[('forfaitaires', 'Forfaitaires'), ('provisionnelles', 'Provisionnelles')], default='forfaitaires', max_length=20, verbose_name='Type de charges'),
        ),
    ]
