# Generated by Django 5.1.7 on 2025-06-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0014_bailspecificites_type_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataire',
            name='caution_requise',
            field=models.BooleanField(default=False, help_text='Indique si une caution est requise pour ce locataire'),
        ),
    ]
