# Generated by Django 5.1.7 on 2025-06-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0015_locataire_caution_requise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='etage',
        ),
    ]
