# Generated by Django 5.1.7 on 2025-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0016_remove_bien_etage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='etage',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
