# Generated by Django 5.1.7 on 2025-06-16 18:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0017_bien_etage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('bail', 'Contrat de bail'), ('grille_vetuste', 'Grille de vétusté'), ('notice_information', "Notice d'information"), ('diagnostic', 'Diagnostic'), ('autre', 'Autre document')], help_text='Type de document', max_length=50)),
                ('nom_original', models.CharField(help_text='Nom original du fichier uploadé', max_length=255)),
                ('fichier', models.FileField(help_text='Fichier du document', upload_to='documents/%Y/%m/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bail', models.ForeignKey(blank=True, help_text='Bail auquel ce document est rattaché', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bail.bailspecificites')),
                ('bien', models.ForeignKey(blank=True, help_text='Bien auquel ce document est rattaché', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bail.bien')),
                ('uploade_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a uploadé ce document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'bail_document',
                'ordering': ['-date_creation'],
            },
        ),
    ]
