# Generated by Django 5.1.7 on 2025-06-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0018_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='fichier',
            new_name='file',
        ),
    ]
