# Generated by Django 5.1.7 on 2025-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0019_rename_fichier_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailspecificites',
            name='prix_reference',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='nb_pieces',
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='rent_price_id',
            field=models.IntegerField(blank=True, help_text='ID du RentPrice de référence (base rent_control)', null=True),
        ),
    ]
