# Generated by Django 5.1.7 on 2025-06-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bail', '0020_remove_bailspecificites_prix_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailspecificites',
            name='complement_loyer',
        ),
        migrations.AddField(
            model_name='bailspecificites',
            name='justificatif_complement_loyer',
            field=models.TextField(blank=True, help_text="Justification du complément de loyer en cas de dépassement du plafond d'encadrement", verbose_name='Justification du complément de loyer'),
        ),
    ]
