# Generated by Django 5.1.7 on 2025-11-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TsaSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de génération du timestamp')),
            ],
            options={
                'verbose_name': 'TSA Serial',
                'verbose_name_plural': 'TSA Serials',
                'ordering': ['-id'],
            },
        ),
    ]
