# Generated by Django 5.1.7 on 2025-08-05 09:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bail', '0003_bailsignaturerequest_otp_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatLieux',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_etat_lieux', models.CharField(choices=[('entree', "État des lieux d'entrée"), ('sortie', 'État des lieux de sortie')], help_text="Type d'état des lieux", max_length=10)),
                ('pdf', models.FileField(blank=True, help_text="PDF de l'état des lieux généré", null=True, upload_to='etat_lieux_pdfs/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_lieux', to='bail.bailspecificites')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtatLieuxPiece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom de la pièce', max_length=100)),
                ('type_piece', models.CharField(help_text='Type de pièce', max_length=50)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_etat_lieux', to='bail.bien')),
            ],
            options={
                'verbose_name': 'Pièce état des lieux',
                'verbose_name_plural': 'Pièces état des lieux',
                'unique_together': {('bien', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='EtatLieuxPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_key', models.CharField(help_text="Clé de l'élément (sol, murs, etc.)", max_length=50)),
                ('photo_index', models.IntegerField(help_text='Index de la photo pour cet élément')),
                ('image', models.ImageField(help_text="Photo de l'élément", upload_to='etat_lieux_photos/')),
                ('nom_original', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('piece', models.ForeignKey(help_text='Pièce à laquelle cette photo est associée', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='etat_lieux.etatlieuxpiece')),
            ],
            options={
                'verbose_name': 'Photo état des lieux',
                'verbose_name_plural': 'Photos état des lieux',
                'ordering': ['piece', 'element_key', 'photo_index'],
            },
        ),
        migrations.CreateModel(
            name='EtatLieuxSignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='Ordre de signature')),
                ('link_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='etat_lieux_signatures/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('bailleur_signataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etat_lieux_signatures_bailleur', to='bail.personne')),
                ('etat_lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='etat_lieux.etatlieux')),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etat_lieux_signatures_locataire', to='bail.locataire')),
            ],
            options={
                'verbose_name': 'Demande signature état des lieux',
                'verbose_name_plural': 'Demandes signature état des lieux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EtatLieuxPieceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elements', models.JSONField(default=dict, help_text='États des différents éléments de la pièce')),
                ('equipments', models.JSONField(default=list, help_text='Liste des équipements de la pièce')),
                ('mobilier', models.JSONField(default=list, help_text='Liste du mobilier de la pièce')),
                ('etat_lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_details', to='etat_lieux.etatlieux')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_etat_lieux', to='etat_lieux.etatlieuxpiece')),
            ],
            options={
                'verbose_name': 'Détail pièce état des lieux',
                'verbose_name_plural': 'Détails pièces état des lieux',
                'unique_together': {('etat_lieux', 'piece')},
            },
        ),
    ]
