# Generated by Django 5.1.7 on 2025-08-20 14:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatLieux',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Document PDF')),
                ('latest_pdf', models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Dernière version signée')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_etat_lieux', models.CharField(choices=[('entree', "État des lieux d'entrée"), ('sortie', 'État des lieux de sortie')], max_length=10)),
                ('date_etat_lieux', models.DateField(default=django.utils.timezone.now)),
                ('nombre_cles', models.JSONField(default=dict)),
                ('compteurs', models.JSONField(default=dict)),
                ('equipements_chauffage', models.JSONField(default=dict)),
                ('grille_vetuste_pdf', models.FileField(blank=True, null=True, upload_to='etat_lieux_pdfs/', verbose_name='Grille de vétusté PDF')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_lieux', to='location.location')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'db_table': 'etat_lieux_etatlieux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtatLieuxPiece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom de la pièce', max_length=100)),
                ('type_piece', models.CharField(help_text='Type de pièce', max_length=50)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_etat_lieux', to='location.bien')),
            ],
            options={
                'verbose_name': 'Pièce état des lieux',
                'verbose_name_plural': 'Pièces état des lieux',
                'db_table': 'etat_lieux_piece',
                'unique_together': {('bien', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='EtatLieuxPieceDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elements', models.JSONField(default=dict, help_text='États des différents éléments de la pièce')),
                ('equipments', models.JSONField(default=list, help_text='Liste des équipements de la pièce')),
                ('mobilier', models.JSONField(default=list, help_text='Liste du mobilier de la pièce')),
                ('degradations', models.JSONField(blank=True, default=list)),
                ('etat_lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_details', to='etat_lieux.etatlieux')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_etat_lieux', to='etat_lieux.etatlieuxpiece')),
            ],
            options={
                'verbose_name': 'Détail pièce état des lieux',
                'verbose_name_plural': 'Détails pièces état des lieux',
                'db_table': 'etat_lieux_piecedetail',
                'unique_together': {('etat_lieux', 'piece')},
            },
        ),
        migrations.CreateModel(
            name='EtatLieuxPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_key', models.CharField(help_text="Clé de l'élément (sol, murs, etc.)", max_length=50)),
                ('photo_index', models.IntegerField(help_text='Index de la photo pour cet élément')),
                ('image', models.ImageField(help_text="Photo de l'élément", upload_to='etat_lieux_photos/')),
                ('nom_original', models.CharField(help_text='Nom original du fichier', max_length=255)),
                ('piece_detail', models.ForeignKey(help_text='Détail de pièce spécifique à un état des lieux', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='etat_lieux.etatlieuxpiecedetail')),
            ],
            options={
                'verbose_name': 'Photo état des lieux',
                'verbose_name_plural': 'Photos état des lieux',
                'db_table': 'etat_lieux_photo',
                'ordering': ['piece_detail', 'element_key', 'photo_index'],
            },
        ),
        migrations.CreateModel(
            name='EtatLieuxSignatureRequest',
            fields=[
                ('order', models.PositiveSmallIntegerField(help_text='Ordre de signature dans le processus')),
                ('otp', models.CharField(blank=True, default='', max_length=6)),
                ('otp_generated_at', models.DateTimeField(blank=True, help_text="Horodatage de génération de l'OTP (pour vérifier l'expiration)", null=True)),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('bailleur_signataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etat_lieux_signatures_bailleur', to='location.personne')),
                ('etat_lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='etat_lieux.etatlieux')),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etat_lieux_signatures_locataire', to='location.locataire')),
            ],
            options={
                'verbose_name': 'Demande signature état des lieux',
                'verbose_name_plural': 'Demandes signature état des lieux',
                'ordering': ['order'],
            },
        ),
    ]
