# Generated by Django 5.1.7 on 2025-10-03 21:53

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0001_initial'),
        ('location', '0002_historicalbien_historicallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEtatLieux',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Document PDF')),
                ('latest_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Dernière version signée')),
                ('type_etat_lieux', models.CharField(choices=[('entree', "État des lieux d'entrée"), ('sortie', 'État des lieux de sortie')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('date_etat_lieux', models.DateField(default=django.utils.timezone.now)),
                ('nombre_cles', models.JSONField(default=dict)),
                ('compteurs', models.JSONField(blank=True, default=None, null=True)),
                ('commentaires_generaux', models.TextField(blank=True, default=None, help_text="Commentaires généraux sur l'état des lieux", null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('grille_vetuste_pdf', models.TextField(blank=True, max_length=100, null=True, verbose_name='Grille de vétusté PDF')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical État des lieux',
                'verbose_name_plural': 'historical États des lieux',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='etatlieux',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='etatlieux',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etatlieux',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='etatlieux',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SIGNING', 'SIGNED'])), fields=('location', 'type_etat_lieux'), name='unique_signing_or_signed_edl_per_location_and_type'),
        ),
        migrations.AddField(
            model_name='historicaletatlieux',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaletatlieux',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location'),
        ),
    ]
