# Generated by Django 5.1.7 on 2025-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0001_initial'),
        ('location', '0011_add_null_to_identifiant_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlieux',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='etatlieux',
            unique_together={('location', 'type_etat_lieux')},
        ),
    ]
