# Generated by Django 5.1.7 on 2025-09-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etatlieuxequipement',
            old_name='etat',
            new_name='state',
        ),
    ]
