# Generated by Django 5.1.7 on 2025-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0002_etatlieux_status_alter_etatlieux_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlieux',
            name='annexes_privatives_equipements',
            field=models.JSONField(default=dict),
        ),
    ]
