# Generated by Django 5.1.7 on 2025-11-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0002_historicaletatlieux_alter_etatlieux_unique_together_and_more'),
        ('location', '0011_alter_personne_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlieuxsignaturerequest',
            name='mandataire',
            field=models.ForeignKey(blank=True, help_text='Mandataire qui signe pour le compte du bailleur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etat_lieux_signature_requests', to='location.mandataire'),
        ),
        migrations.AlterUniqueTogether(
            name='etatlieuxsignaturerequest',
            unique_together={('etat_lieux', 'bailleur_signataire'), ('etat_lieux', 'locataire'), ('etat_lieux', 'mandataire')},
        ),
    ]
