# Generated by Django 5.1.7 on 2025-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0002_rename_etat_to_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatlieux',
            name='compteurs',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
