# Generated by Django 5.1.7 on 2025-08-07 09:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0002_etatlieuxsignaturerequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatlieuxsignaturerequest',
            name='link_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='etatlieuxsignaturerequest',
            name='order',
            field=models.PositiveSmallIntegerField(help_text='Ordre de signature dans le processus'),
        ),
        migrations.AlterField(
            model_name='etatlieuxsignaturerequest',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='etatlieuxsignaturerequest',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage de génération de l'OTP (pour vérifier l'expiration)", null=True),
        ),
        migrations.AlterField(
            model_name='etatlieuxsignaturerequest',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
