# Generated by Django 5.1.7 on 2025-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0003_alter_etatlieuxsignaturerequest_link_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlieux',
            name='latest_pdf',
            field=models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Dernière version signée'),
        ),
        migrations.AlterField(
            model_name='etatlieux',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='signed_documents/', verbose_name='Document PDF'),
        ),
    ]
