# Generated by Django 5.1.7 on 2025-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0003_alter_etatlieux_compteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlieuxequipement',
            name='quantity',
            field=models.IntegerField(blank=True, help_text="Quantité de l'équipement (pour les équipements comptables)", null=True),
        ),
    ]
