# Generated by Django 5.1.7 on 2025-11-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0004_etatlieux_mandataire_doit_signer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatlieux',
            name='grille_vetuste_pdf',
        ),
        migrations.RemoveField(
            model_name='historicaletatlieux',
            name='grille_vetuste_pdf',
        ),
    ]
