# Generated by Django 5.1.7 on 2025-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0004_add_quantity_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlieux',
            name='commentaires_generaux',
            field=models.TextField(blank=True, default=None, help_text="Commentaires généraux sur l'état des lieux", null=True),
        ),
    ]
