# Generated by Django 5.1.7 on 2025-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0004_etatlieux_latest_pdf_alter_etatlieux_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlieux',
            name='compteurs',
            field=models.JSONField(blank=True, default=dict, help_text='Relevés des compteurs'),
        ),
        migrations.AddField(
            model_name='etatlieux',
            name='equipements_chauffage',
            field=models.JSONField(blank=True, default=dict, help_text='Équipements de chauffage et eau chaude'),
        ),
        migrations.AddField(
            model_name='etatlieux',
            name='nombre_cles',
            field=models.JSONField(blank=True, default=dict, help_text='Nombre et types de clés remises'),
        ),
    ]
