# Generated by Django 5.1.7 on 2025-11-17 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("etat_lieux", "0005_remove_etatlieux_grille_vetuste_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etatlieuxphoto",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                help_text="Équipement associé",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="etat_lieux.etatlieuxequipement",
            ),
        ),
    ]
