# Generated by Django 5.1.7 on 2025-08-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0005_etatlieux_compteurs_etatlieux_equipements_chauffage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etatlieuxphoto',
            options={'ordering': ['piece_detail', 'element_key', 'photo_index'], 'verbose_name': 'Photo état des lieux', 'verbose_name_plural': 'Photos état des lieux'},
        ),
        migrations.AddField(
            model_name='etatlieuxphoto',
            name='piece_detail',
            field=models.ForeignKey(blank=True, help_text='Détail de pièce spécifique à un état des lieux', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='etat_lieux.etatlieuxpiecedetail'),
        ),
        migrations.AlterField(
            model_name='etatlieuxphoto',
            name='piece',
            field=models.ForeignKey(blank=True, help_text='Ancienne relation - à supprimer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_photos', to='etat_lieux.etatlieuxpiece'),
        ),
    ]
