# Generated by Django 5.2.8 on 2025-12-05 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0006_alter_etatlieuxphoto_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlieuxsignaturerequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text="Date d'annulation de la demande de signature", null=True),
        ),
        migrations.AddField(
            model_name='etatlieuxsignaturerequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant annulé la demande de signature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_cancelled', to=settings.AUTH_USER_MODEL),
        ),
    ]
