# Generated by Django 5.1.7 on 2025-08-11 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0006_alter_etatlieuxphoto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatlieuxphoto',
            name='piece',
        ),
        migrations.AlterField(
            model_name='etatlieuxphoto',
            name='piece_detail',
            field=models.ForeignKey(help_text='Détail de pièce spécifique à un état des lieux', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='etat_lieux.etatlieuxpiecedetail'),
        ),
    ]
