# Generated by Django 5.2.8 on 2025-12-05 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_lieux', '0007_etatlieuxsignaturerequest_cancelled_at_and_more'),
        ('location', '0018_historicalpersonne_historicalsociete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='etatlieuxsignaturerequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='etatlieuxsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('etat_lieux', 'bailleur_signataire'), name='unique_edl_bailleur_signataire_active'),
        ),
        migrations.AddConstraint(
            model_name='etatlieuxsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('etat_lieux', 'locataire'), name='unique_edl_locataire_active'),
        ),
        migrations.AddConstraint(
            model_name='etatlieuxsignaturerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('etat_lieux', 'mandataire'), name='unique_edl_mandataire_active'),
        ),
    ]
