# Generated by Django 5.1.7 on 2025-10-02 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé')], default='draft', max_length=20)),
                ('mois', models.CharField(help_text='Mois en français (janvier, février, etc.)', max_length=20)),
                ('annee', models.PositiveIntegerField(help_text='Année de la quittance')),
                ('date_paiement', models.DateField(help_text='Date à laquelle le loyer a été payé')),
                ('montant_loyer', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant du loyer hors charges pour cette quittance', max_digits=10, null=True)),
                ('montant_charges', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant des charges pour cette quittance', max_digits=10, null=True)),
                ('pdf', models.FileField(blank=True, help_text='PDF de la quittance généré', null=True, upload_to='quittances_pdfs/')),
                ('locataires', models.ManyToManyField(blank=True, help_text='Locataire(s) concerné(s) par cette quittance. Si vide, tous les locataires de la location sont concernés.', related_name='quittances', to='location.locataire')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='location.location')),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'db_table': 'quittance_quittance',
                'ordering': ['-created_at'],
            },
        ),
    ]
