# Generated by Django 5.1.7 on 2025-08-05 12:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bail', '0003_bailsignaturerequest_otp_generated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mois', models.CharField(help_text='Mois en français (janvier, février, etc.)', max_length=20)),
                ('annee', models.PositiveIntegerField(help_text='Année de la quittance')),
                ('date_paiement', models.DateField(help_text='Date à laquelle le loyer a été payé')),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf', models.FileField(blank=True, help_text='PDF de la quittance généré', null=True, upload_to='quittances_pdfs/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='bail.bailspecificites')),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'ordering': ['-date_creation'],
                'unique_together': {('bail', 'mois', 'annee')},
            },
        ),
    ]
