# Generated by Django 5.1.7 on 2025-10-03 21:53

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_historicalbien_historicallocation'),
        ('quittance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalQuittance',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('mois', models.CharField(help_text='Mois en français (janvier, février, etc.)', max_length=20)),
                ('annee', models.PositiveIntegerField(help_text='Année de la quittance')),
                ('date_paiement', models.DateField(help_text='Date à laquelle le loyer a été payé')),
                ('montant_loyer', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant du loyer hors charges pour cette quittance', max_digits=10, null=True)),
                ('montant_charges', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Montant des charges pour cette quittance', max_digits=10, null=True)),
                ('pdf', models.TextField(blank=True, help_text='PDF de la quittance généré', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.location')),
            ],
            options={
                'verbose_name': 'historical Quittance',
                'verbose_name_plural': 'historical Quittances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
