# Generated by Django 5.1.7 on 2025-09-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quittance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quittance',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('signing', 'En cours de signature'), ('signed', 'Signé et finalisé')], default='draft', max_length=20),
        ),
    ]
