# Generated by Django 5.1.7 on 2025-06-23 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Adresse email pour la notification', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('feature', models.CharField(choices=[('quittance', 'Quittance automatique'), ('etat_des_lieux', 'État des lieux digital')], help_text='Fonctionnalité demandée', max_length=20)),
                ('role', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('gestionnaire', 'Gestionnaire immobilier'), ('locataire', 'Locataire'), ('comptable', 'Comptable'), ('autre', 'Autre')], help_text="Rôle de l'utilisateur", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False, help_text='Notification envoyée')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification_requests',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'feature')},
            },
        ),
    ]
