# Generated by Django 5.1.7 on 2025-11-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrequest',
            name='feature',
            field=models.CharField(choices=[('assurance', "Comparateur d'assurances")], help_text='Fonctionnalité demandée', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationrequest',
            name='role',
            field=models.CharField(choices=[('proprietaire', 'Propriétaire'), ('mandataire', 'Mandataire immobilier'), ('locataire', 'Locataire'), ('comptable', 'Comptable'), ('autre', 'Autre')], help_text="Rôle de l'utilisateur", max_length=20),
        ),
    ]
