# Generated by Django 5.2.8 on 2025-12-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationrequest_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrequest',
            name='feature',
            field=models.CharField(choices=[('assurance', "Comparateur d'assurances"), ('demenagement', 'Service déménagement'), ('stockage', 'Box de stockage'), ('energie', 'Énergie (électricité/gaz)'), ('eau', "Fournisseur d'eau"), ('internet', 'Internet/Box')], help_text='Fonctionnalité demandée', max_length=20),
        ),
    ]
