"""
Configuration des équipements pour les pièces d'un logement.
Source unique de vérité pour les équipements disponibles.

Tous les équipements (y compris le mobilier) sont stockés dans
EtatLieuxPieceDetail.equipments pour simplifier la gestion.
"""

# Équipements automatiques pour TOUTES les pièces (toujours présents)
EQUIPEMENTS_AUTOMATIQUES = [
    {"id": "murs", "label": "Murs", "icon": "🧱"},
    {"id": "sol", "label": "Sol", "icon": "🟫"},
    {"id": "plafond", "label": "Plafond", "icon": "⬜"},
    {
        "id": "eclairage_interrupteurs",
        "label": "Éclairages et interrupteurs",
        "icon": "💡",
    },
    {"id": "prises_electriques", "label": "Prises électriques", "icon": "🔌"},
]

# Équipements optionnels communs à toutes les pièces
EQUIPEMENTS_COMMUNS = [
    {"id": "portes", "label": "Portes", "icon": "🚪"},
    {"id": "vitrages_volets", "label": "Vitrages/Volets", "icon": "🪟"},
    {"id": "radiateur", "label": "Radiateur", "icon": "🔥"},
    {"id": "rideaux_stores", "label": "Rideaux/Stores", "icon": "🪞"},
    {"id": "luminaires_plafonniers", "label": "Luminaires/Plafonniers", "icon": "💡"},
    {"id": "lampes_appliques", "label": "Lampes/Appliques", "icon": "🛋️"},
]

# Équipements spécifiques par type de pièce
# Tout est unifié dans "equipments" (y compris le mobilier pour les meublés)
EQUIPEMENTS_SPECIFIQUES = {
    "kitchen": {
        "equipments": [
            {
                "id": "placards_tiroirs",
                "label": "Placards et tiroirs",
                "icon": "🗄️",
                "is_countable": True,
            },
            {
                "id": "evier_robinetterie",
                "label": "Évier et robinetterie",
                "icon": "🚰",
                "is_countable": True,
            },
            {"id": "plaque_cuisson", "label": "Plaque de cuisson", "icon": "🔥"},
            {"id": "four", "label": "Four", "icon": "🔥"},
            {"id": "microonde", "label": "Micro-ondes", "icon": "📡"},
            {"id": "hotte", "label": "Hotte", "icon": "💨"},
            {"id": "refrigerateur", "label": "Réfrigérateur", "icon": "❄️"},
            {"id": "congelateur", "label": "Congélateur", "icon": "🧊"},
            {"id": "cuisiniere", "label": "Cuisinière", "icon": "♨️"},
            {"id": "grille_pain", "label": "Grille-pain", "icon": "🍞"},
            {"id": "bouilloire", "label": "Bouilloire", "icon": "☕"},
            {"id": "cafetiere", "label": "Cafetière", "icon": "☕"},
            {"id": "lave_vaisselle", "label": "Lave-vaisselle", "icon": "🍽️"},
            # Mobilier (si meublé)
            {
                "id": "chaise_cuisine",
                "label": "Chaise",
                "icon": "🪑",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "table_cuisine",
                "label": "Table",
                "icon": "🪑",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "buffet_cuisine",
                "label": "Buffet",
                "icon": "🗄️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "tabouret_cuisine",
                "label": "Tabouret",
                "icon": "🪑",
                "furnished_only": True,
                "is_countable": True,
            },
            # Matériel d'entretien ménager adapté
            {
                "id": "aspirateur",
                "label": "Aspirateur",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "balais",
                "label": "Balais",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "balayettes",
                "label": "Balayettes",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "pelles",
                "label": "Pelles",
                "icon": "🗑️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "seaux",
                "label": "Seaux",
                "icon": "🪣",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "torchons",
                "label": "Torchons",
                "icon": "🧽",
                "furnished_only": True,
                "is_countable": True,
            },
            # Linge de maison et entretien du linge
            {
                "id": "lave_linge",
                "label": "Lave-linge",
                "icon": "🌀",
                "furnished_only": True,
            },
            {
                "id": "seche_linge",
                "label": "Sèche-linge",
                "icon": "♨️",
                "furnished_only": True,
            },
            {
                "id": "fer_repasser",
                "label": "Fer à repasser",
                "icon": "👔",
                "furnished_only": True,
            },
            {
                "id": "nappes",
                "label": "Nappes",
                "icon": "🍽️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Vaisselle et ustensiles de cuisine
            {
                "id": "assiettes",
                "label": "Assiettes",
                "icon": "🍽️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "fourchettes",
                "label": "Fourchettes",
                "icon": "🍴",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "cuillers",
                "label": "Cuillères",
                "icon": "🥄",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "couteaux",
                "label": "Couteaux",
                "icon": "🔪",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "verres",
                "label": "Verres",
                "icon": "🥃",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "bols_tasses",
                "label": "Bols / Tasses",
                "icon": "☕",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "ouvre_boite",
                "label": "Tire-bouchon / Décapsuleur / Ouvre-boîte",
                "icon": "🍾",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "carafes",
                "label": "Carafes",
                "icon": "🍶",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "planches_decouper",
                "label": "Planches à découper",
                "icon": "🪵",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "plats_saladiers",
                "label": "Plats / Saladiers",
                "icon": "🥗",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "passoires",
                "label": "Passoires",
                "icon": "🕳️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "poeles",
                "label": "Poêles",
                "icon": "🍳",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "casseroles",
                "label": "Casseroles",
                "icon": "🍲",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "egouttoir",
                "label": "Égouttoir",
                "icon": "🍽️",
                "furnished_only": True,
                "is_countable": True,
            },
        ],
    },
    "bathroom": {
        "equipments": [
            {"id": "lavabo", "label": "Lavabo", "icon": "🚿"},
            {"id": "robinet", "label": "Robinet", "icon": "🚰"},
            {"id": "colonne_douche", "label": "Colonne de douche", "icon": "🚿"},
            {"id": "baignoire", "label": "Baignoire", "icon": "🛁"},
            {"id": "douche", "label": "Douche", "icon": "🚿"},
            {"id": "meuble_sdb", "label": "Meuble", "icon": "🗄️"},
            {
                "id": "placard_sdb",
                "label": "Placard",
                "icon": "🗄️",
                "is_countable": True,
            },
            {"id": "wc_sdb", "label": "WC", "icon": "🚽"},
            # Matériel d'entretien ménager adapté
            {
                "id": "aspirateur",
                "label": "Aspirateur",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "balais",
                "label": "Balais",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "balayettes",
                "label": "Balayettes",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "pelles",
                "label": "Pelles",
                "icon": "🗑️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "seaux",
                "label": "Seaux",
                "icon": "🪣",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "torchons",
                "label": "Torchons",
                "icon": "🧽",
                "furnished_only": True,
                "is_countable": True,
            },
            # Linge de maison et entretien du linge
            {
                "id": "lave_linge",
                "label": "Lave-linge",
                "icon": "🌀",
                "furnished_only": True,
            },
            {
                "id": "seche_linge",
                "label": "Sèche-linge",
                "icon": "♨️",
                "furnished_only": True,
            },
            {
                "id": "fer_repasser",
                "label": "Fer à repasser",
                "icon": "👔",
                "furnished_only": True,
            },
            {
                "id": "peignoirs_bain",
                "label": "Peignoirs de bain",
                "icon": "🧖",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "serviettes",
                "label": "Serviettes",
                "icon": "🧻",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "gants",
                "label": "Gants",
                "icon": "🧤",
                "furnished_only": True,
                "is_countable": True,
            },
        ],
    },
    "wc": {
        "equipments": [
            {"id": "wc", "label": "WC", "icon": "🚽"},
            {"id": "lavabo_wc", "label": "Lavabo", "icon": "🚿"},
            {"id": "meuble_lave_main", "label": "Meuble lave-main", "icon": "🗄️"},
            {"id": "placard_wc", "label": "Placard", "icon": "🗄️", "is_countable": True},
        ],
    },
    "bedroom": {
        "equipments": [
            {
                "id": "placard_chambre",
                "label": "Placard",
                "icon": "🗄️",
                "is_countable": True,
            },
            # Mobilier (si meublé)
            {
                "id": "lit_simple",
                "label": "Lit simple",
                "icon": "🛏️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "lit_double",
                "label": "Lit double",
                "icon": "🛏️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "chaise_chambre",
                "label": "Chaise",
                "icon": "🪑",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "table_chevet",
                "label": "Table de chevet",
                "icon": "🗄️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "bureau_chambre",
                "label": "Bureau",
                "icon": "🖥️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "commode_chambre",
                "label": "Commode",
                "icon": "🗄️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Linge de maison et entretien du linge
            {
                "id": "peignoirs_bain",
                "label": "Peignoirs de bain",
                "icon": "🧖",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "serviettes",
                "label": "Serviettes",
                "icon": "🧻",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "gants",
                "label": "Gants",
                "icon": "🧤",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "coussins",
                "label": "Coussins",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Divertissement
            {
                "id": "television",
                "label": "Télévision",
                "icon": "📺",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "videoprojecteur",
                "label": "Vidéoprojecteur",
                "icon": "📽️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Literie
            {
                "id": "lit",
                "label": "Lit",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "matelas",
                "label": "Matelas",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "taies",
                "label": "Taies",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "oreillers",
                "label": "Oreillers",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "draps",
                "label": "Draps",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "couette_couverture",
                "label": "Couette/Couverture/Couvre-lit",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "housse_couette",
                "label": "Housse de couette",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "alaise",
                "label": "Alaise",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
        ],
    },
    "living": {
        "equipments": [
            {
                "id": "placard_sejour",
                "label": "Placard",
                "icon": "🗄️",
                "is_countable": True,
            },
            # Mobilier (si meublé)
            {
                "id": "chaise_sejour",
                "label": "Chaise",
                "icon": "🪑",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "tabouret_sejour",
                "label": "Tabouret",
                "icon": "🪑",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "table_sejour",
                "label": "Table",
                "icon": "🪑",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "canape",
                "label": "Canapé",
                "icon": "🛋️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "fauteuil",
                "label": "Fauteuil",
                "icon": "🪑",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "bureau_sejour",
                "label": "Bureau",
                "icon": "🖥️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "buffet_sejour",
                "label": "Buffet",
                "icon": "🗄️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "commode_sejour",
                "label": "Commode",
                "icon": "🗄️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Matériel d'entretien ménager adapté
            {
                "id": "aspirateur",
                "label": "Aspirateur",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "balais",
                "label": "Balais",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "balayettes",
                "label": "Balayettes",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "pelles",
                "label": "Pelles",
                "icon": "🗑️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "seaux",
                "label": "Seaux",
                "icon": "🪣",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "torchons",
                "label": "Torchons",
                "icon": "🧽",
                "furnished_only": True,
                "is_countable": True,
            },
            # Linge de maison et entretien du linge
            {
                "id": "fer_repasser",
                "label": "Fer à repasser",
                "icon": "👔",
                "furnished_only": True,
            },
            {
                "id": "coussins",
                "label": "Coussins",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Vaisselle et ustensiles de cuisine
            {
                "id": "assiettes",
                "label": "Assiettes",
                "icon": "🍽️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "fourchettes",
                "label": "Fourchettes",
                "icon": "🍴",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "cuillers",
                "label": "Cuillères",
                "icon": "🥄",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "couteaux",
                "label": "Couteaux",
                "icon": "🔪",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "verres",
                "label": "Verres",
                "icon": "🥃",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "bols_tasses",
                "label": "Bols / Tasses",
                "icon": "☕",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "ouvre_boite",
                "label": "Tire-bouchon / Décapsuleur / Ouvre-boîte",
                "icon": "🍾",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "carafes",
                "label": "Carafes",
                "icon": "🍶",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "planches_decouper",
                "label": "Planches à découper",
                "icon": "🪥",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "plats_saladiers",
                "label": "Plats / Saladiers",
                "icon": "🥗",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "passoires",
                "label": "Passoires",
                "icon": "🕳️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "poeles",
                "label": "Poêles",
                "icon": "🍳",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "casseroles",
                "label": "Casseroles",
                "icon": "🍲",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "egouttoir",
                "label": "Égouttoir",
                "icon": "🍽️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Divertissement
            {
                "id": "television",
                "label": "Télévision",
                "icon": "📺",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "videoprojecteur",
                "label": "Vidéoprojecteur",
                "icon": "📽️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Literie
            {
                "id": "lit",
                "label": "Lit",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "matelas",
                "label": "Matelas",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "taies",
                "label": "Taies",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "oreillers",
                "label": "Oreillers",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "draps",
                "label": "Draps",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "couette_couverture",
                "label": "Couette/Couverture/Couvre-lit",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "housse_couette",
                "label": "Housse de couette",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "alaise",
                "label": "Alaise",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
        ],
    },
    "other": {
        "equipments": [
            # Matériel d'entretien ménager adapté
            {
                "id": "aspirateur",
                "label": "Aspirateur",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "balais",
                "label": "Balais",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "balayettes",
                "label": "Balayettes",
                "icon": "🧹",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "pelles",
                "label": "Pelles",
                "icon": "🗑️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "seaux",
                "label": "Seaux",
                "icon": "🪣",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "torchons",
                "label": "Torchons",
                "icon": "🧽",
                "furnished_only": True,
                "is_countable": True,
            },
            # Linge de maison et entretien du linge
            {
                "id": "lave_linge",
                "label": "Lave-linge",
                "icon": "🌀",
                "furnished_only": True,
            },
            {
                "id": "seche_linge",
                "label": "Sèche-linge",
                "icon": "♨️",
                "furnished_only": True,
            },
            {
                "id": "fer_repasser",
                "label": "Fer à repasser",
                "icon": "👔",
                "furnished_only": True,
            },
            {
                "id": "nappes",
                "label": "Nappes",
                "icon": "🍽️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "coussins",
                "label": "Coussins",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Vaisselle et ustensiles de cuisine
            {
                "id": "assiettes",
                "label": "Assiettes",
                "icon": "🍽️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "fourchettes",
                "label": "Fourchettes",
                "icon": "🍴",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "cuillers",
                "label": "Cuillères",
                "icon": "🥄",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "couteaux",
                "label": "Couteaux",
                "icon": "🔪",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "verres",
                "label": "Verres",
                "icon": "🥃",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "bols_tasses",
                "label": "Bols / Tasses",
                "icon": "☕",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "ouvre_boite",
                "label": "Tire-bouchon / Décapsuleur / Ouvre-boîte",
                "icon": "🍾",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "carafes",
                "label": "Carafes",
                "icon": "🍶",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "planches_decouper",
                "label": "Planches à découper",
                "icon": "🪥",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "plats_saladiers",
                "label": "Plats / Saladiers",
                "icon": "🥗",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "passoires",
                "label": "Passoires",
                "icon": "🕳️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "poeles",
                "label": "Poêles",
                "icon": "🍳",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "casseroles",
                "label": "Casseroles",
                "icon": "🍲",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "egouttoir",
                "label": "Égouttoir",
                "icon": "🍽️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Divertissement
            {
                "id": "television",
                "label": "Télévision",
                "icon": "📺",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "videoprojecteur",
                "label": "Vidéoprojecteur",
                "icon": "📽️",
                "furnished_only": True,
                "is_countable": True,
            },
            # Literie
            {
                "id": "lit",
                "label": "Lit",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "matelas",
                "label": "Matelas",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "taies",
                "label": "Taies",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "oreillers",
                "label": "Oreillers",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "draps",
                "label": "Draps",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "couette_couverture",
                "label": "Couette/Couverture/Couvre-lit",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "housse_couette",
                "label": "Housse de couette",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
            {
                "id": "alaise",
                "label": "Alaise",
                "icon": "🛜️",
                "furnished_only": True,
                "is_countable": True,
            },
        ],
    },
    "room": {
        "equipments": [],
    },
}


def get_all_equipements_config():
    """
    Retourne la configuration complète des équipements.
    Utilisé pour la génération des schemas Zod et l'API.
    """
    return {
        "automatiques": EQUIPEMENTS_AUTOMATIQUES,
        "communs": EQUIPEMENTS_COMMUNS,
        "specifiques": EQUIPEMENTS_SPECIFIQUES,
    }
